/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pedromanoel.reactive;

public class App {

    public static void main(String[] args) {
        new FirstExample().run();
    }
}
